name: Deploy Node.js App

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/devops_key1
          chmod 600 ~/.ssh/devops_key1

      - name: Create inventory file
        run: |
          cat <<EOF > ansible/inventory.ini
          [webservers]
          web1 ansible_host=${{ secrets.EC2_HOST }} ansible_user=${{ secrets.EC2_USER }} ansible_ssh_private_key_file=~/.ssh/devops_key1

          [webservers:vars]
          ansible_ssh_common_args='-o StrictHostKeyChecking=no'
          EOF

      - name: Run Ansible playbook
        run: ansible-playbook -i inventory.ini node_service.yml --tags app
        working-directory: ansible
