name: Build and Deploy Node.js App

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  API_IMAGE_NAME: roman102/devops-project-api
  WEB_IMAGE_NAME: roman102/devops-project-web

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push API image
        uses: docker/build-push-action@v6
        with:
          context: ./api
          push: true
          tags: ${{ env.API_IMAGE_NAME }}:latest

      - name: Build and push Web image
        uses: docker/build-push-action@v6
        with:
          context: ./web
          push: true
          tags: ${{ env.WEB_IMAGE_NAME }}:latest

      - name: Install Ansible and Docker collection
        run: |
          sudo apt update
          sudo apt install -y ansible
          ansible-galaxy collection install community.docker

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/devops_key1
          chmod 600 ~/.ssh/devops_key1

      - name: Create inventory file
        run: |
          cat <<EOF > ansible/inventory.ini
          [webservers]
          web1 ansible_host=${{ secrets.EC2_HOST }} ansible_user=${{ secrets.EC2_USER }} ansible_ssh_private_key_file=~/.ssh/devops_key1

          [webservers:vars]
          ansible_ssh_common_args='-o StrictHostKeyChecking=no'
          EOF

      - name: Deploy Web + run blue-green for API
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /opt/app
            docker compose pull web
            docker compose up -d --no-deps web
            ./deploy-blue-green.sh
